### ISSUE TITLE
CRITICAL Parse error at line 1, column 1

### ISSUE THREAD

**Issue by alpter** [alexbruy/qconsolidate#12]
Got this message when try to consolidate file...
> 
Error: Parse error at line 1, column 1: error occurred while parsing element

See here
#https://github.com/alexbruy/qconsolidate/issues/11

**Comment by alpter** [comment]
#https://github.com/danzig666/qconsolidate3/issues/4

**Comment by alexbruy** [comment]
Please check already closed tickets before opening duplicated one. Also read plugin metadata to find out correct bugtracker and author.

**My** plugin is not affected  by this issue

**Comment by alpter** [comment]
@alexbruy it has to do with this

**Comment by alpter** [comment]
@alexbruy it has to do with this
[Error: Parse error at line 1, column 1: error occurred while parsing element in QGIS 3 and 2.18](https://github.com/danzig666/qconsolidate3/issues/4)
