### ISSUE TITLE
Multiple Layers with same name not packaged properly

### ISSUE THREAD

**Issue by Saijin-Naib** [alexbruy/qconsolidate#14]
Went to package a project that had two layers with the same name:
1) Snow_Points_Type_3 as a memory layer with type point
2) Snow_Points_Type_3 as a geopackage non-spatial table

After QConsolidate choosing GPKG as the collect method, both project references reference the same single resultant data: geopackage non-spatial table.

**Comment by alexbruy** [comment]
Not a bug actually, it is by design. Layers are exported using their name as destination file/table name, so if there are two layers with the same name the last one will overwrite previously exported.
