### ISSUE TITLE
qconsolidate failing after 1 shape file copied

### ISSUE THREAD

**Issue by paul736** [alexbruy/qconsolidate#15]
Hi - I have a qgis project costing of typical shape files - point, lines and polygons only. Running QConsolidate throws up an error - "task failed".  It creates a project file + layer file, but only copies 1 shape file, and then stops.   I'm using the latest qgis 3.14, on Windows 10.  In the QConsolidate dialog box I'm saving to a local directory, and all files are stored locally.  I've selecting ESRI shape file as the file format.  

Any help would be great.  Thanks!

**Comment by alexbruy** [comment]
Not reproducible here. Please provide more information as well as test data and project.

**Comment by paul736** [comment]
Hi - ok so this is totally bizarre, but its working now using the same test data I was using yesterday.  I've now tested on a few different projects and it seems to be working.  Sorry for the false alarm!
