### ISSUE TITLE
Wrong layers name

### ISSUE THREAD

**Issue by niubii** [alexbruy/qconsolidate#16]
Hi,

just trying QConsolidate 1.1.0 with QGIS 3.4.5 in Windows 10.
I noticed a strange behavior of the plugin.

I want to make a copy of my current project, that's a collection of about 20 layers into two .gpkg files.

When I choose "Copy to directory" (with .gpkg option), it makes a copy of my project. Layer names still remains as the original.
Instead, if I choose "Geopackage" option, it also makes a copy of my project, but layer names inside the new .gpkg file are changed.

Example:
Layer "Features_between_1-20" will became "Features_Between_120"
Layer "ABC" will became "Abc"

Thus, I'm having problem to apply styles and use saved field calculator functions.

Do you think this could be a bug?
Thank you for your job.

Francesco

**Comment by alexbruy** [comment]
This is not a bug, but intentional behaviour. Probably I will make it optional in next versions.
