### ISSUE TITLE
When exporting raster, creation options are not used

### ISSUE THREAD

**Issue by nicogodet** [alexbruy/qconsolidate#20]
In `exportwriter`, options are not passed when calling `exportWriterLayer`
https://github.com/alexbruy/qconsolidate/blob/f458c5fc4779c2cc8d118d470b37028c42b81851/writers/exportwriter.py#L77

In the definition of `exportWriterLayer`, you allow to pass creation options.
https://github.com/alexbruy/qconsolidate/blob/f458c5fc4779c2cc8d118d470b37028c42b81851/writers/writerbase.py#L186
https://github.com/alexbruy/qconsolidate/blob/f458c5fc4779c2cc8d118d470b37028c42b81851/writers/writerbase.py#L225-L226

Creation options used in `consolidatethread` could be used here.
https://github.com/alexbruy/qconsolidate/blob/f458c5fc4779c2cc8d118d470b37028c42b81851/consolidatethread.py#L233

An alternative would be to use default GDAL creation options set in Qgis settings.

**Comment by alexbruy** [comment]
In fact they are used when necessary.
